# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a37a8148008807b0287107d035ebc72fc2d06bad44d0740c2c719a0e6331b99d82d48e12798f37476776d0d4c11c0ed976ad45af952762053aca9033645125c8

test:
  secret_key_base: b3867c44b398a96a0e05354c9e7494836278e7b50f10a2520058534d9848cda60e383631b16bf2351414377c6c94a126089c6b1e52c65e4cb44b3a04ba960f4d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
